
task :default => [:config]

# I use 'git config' because I can't symlink ~/.gitconfig on Windows. :(
desc 'Configure git for current user.'
task :config do
  puts 'Configuring git.'
  `git config --global user.name "Adam Flanczewski"`
  `git config --global user.email "sl@ckwi.se"`
  `git config --global core.eol lf`
  `git config --global core.autocrlf false`
  `git config --global core.editor vim`
  `git config --global color.ui always`
  `git config --global diff.tool vimdiff`
  `git config --global difftool.prompt false`
  `git config --global alias.c "commit -am"`
end
