
task :default => [:config]

desc "Configure git for current user."
task :config do
  puts 'Configuring git.'
  `git config --global user.name "Adam Flanczewski"`
  `git config --global user.email "sl@ckwi.se"`
  `git config --global core.eol lf`
end
