#!/usr/bin/env ruby

require 'pathname'

HOME                    = Pathname(ENV['HOME'])
EMACS_D                 = HOME + '.emacs.d'
SPACEMACS_D             = HOME + '.spacemacs.d'
SPACEMACS_GIT_DIR       = HOME + 'src' + 'spacemacs'
DOTFILES_SPACEMACS_DIR  = HOME + 'src' + 'dotfiles' + 'spacemacs'
DESKTOP_SHORTCUT        = Pathname('.') + 'spacemacs.desktop'
DESKTOP_SHORTCUT_DIR    = HOME + '.local' + 'share' + 'applications'
GIT_CLONE_CMD           = %|git clone --recursive https://github.com/syl20bnr/spacemacs "#{SPACEMACS_GIT_DIR}"|
MKLINK_EMACS_D_CMD      = %|cmd /c mklink /d "#{EMACS_D.expand_path}" "#{SPACEMACS_GIT_DIR.expand_path}"|
MKLINK_SPACEMACS_D_CMD  = %|cmd /c mklink /d "#{SPACEMACS_D.expand_path}" "#{DOTFILES_SPACEMACS_DIR.expand_path}"|
TAKEOWN_CMD             = %|takeown /f "#{EMACS_D.expand_path}" /r|
CREATE_HOME_CMD         = %|setx HOME "%USERPROFILE%"|

def windows?
  RUBY_PLATFORM.match(/mswin/) || RUBY_PLATFORM.match(/mingw32/)
end

desc "Clone Spacemacs master repository."
task :git_clone do
  if system(GIT_CLONE_CMD)
    puts "Git-cloned Spacemacs to ~/.emacs.d"
  else
    puts "Failed to git-clone Spacemacs!"
    exit 1
  end
end

desc "Fix Windows folder owner permissions."
task :fix_win_perms => [:git_clone] do
  if windows?
    system(TAKEOWN_CMD) || raise("Failed to take ownership of ~/.emacs.d/ files!")
    puts "Took ownership of ~/.emacs.d/"
  end
end

desc "Setup necessary directories/symlinks."
task :setup_dirs do
  begin
    if windows?
      system(MKLINK_EMACS_D_CMD) || raise("Windows ~/.emacs.d/ MKLINK failed")
      system(MKLINK_SPACEMACS_D_CMD) || raise("Windows ~/.spacemacs.d/ MKLINK failed")
      Rake::Task['fix_win_perms'].execute
      Rake::Task['create_home'].execute
    else
      File.symlink(SPACEMACS_GIT_DIR.expand_path, EMACS_D.expand_path)
      File.symlink(DOTFILES_SPACEMACS_DIR.expand_path, SPACEMACS_D.expand_path)
    end
    "Linked directories."
  rescue
    puts "Failed to symlink Spacemacs directory: #$!"
    exit 1
  end
end

desc "Create $HOME for Windows."
task :create_home do
  if windows?
    system(CREATE_HOME_CMD) || raise("Failed to create $HOME for Windows!")
    puts "Created $HOME for Windows."
  end
end

desc "Create desktop shortcut."
task :desktop_shortcut do
  begin
    File.symlink(DESKTOP_SHORTCUT.expand_path, DESKTOP_SHORTCUT_DIR.expand_path)
    puts "Created desktop shortcut."
  rescue
    puts "Failed to symlink desktop shortcut: #$!"
    exit 1
  end
end

desc "Install Spacemacs."
task :default => [:git_clone, :setup_dirs] do
  puts "Spacemacs successfully installed."
end
