#!/usr/bin/env ruby

desc 'Install RVM.'

def distro
  case `uname -a`
  when /ubuntu/i
    return :ubuntu
  when /gentoo/i
    return :gentoo
  end
end

task :install do
  if `which curl`.strip == ''
    if distro == :ubuntu
      `sudo apt-get install build-essential curl`
    elsif distro == :gentoo
      `sudo emerge curl`
    else
      puts 'Hope curl is installed...'
    else
      raise 'curl not installed.'
  end
  if
  ` curl -L https://get.rvm.io | bash -s stable --ruby && source ~/.rvm/scripts/rvm`
  rescue
    puts "RVM failed to install: #$!"
    exit 1
  end
end

task :default => [:install]
