#!/usr/bin/env ruby

require 'pathname'

HOME      = Pathname(ENV['HOME'])
TMUX_PATH = HOME + '/src/dotfiles/tmux/tmux.conf'
TMUX_CONF = HOME + '.tmux.conf'


def symlink_tmuxconf
  File.symlink(TMUX_PATH, TMUX_CONF)
  puts 'Symlinked ~/.tmux.conf'
rescue
  puts "Failed to symlink ~/.tmux.conf: #$!"
end

task :default do
  symlink_tmuxconf
end
