#!/bin/sh

if [ -e "~/.profile" ]; then
    source ~/.profile
fi

if [ -e "~/.bash_profile" ]; then
    source ~/.bash_profile
fi

if [ -d "~/.rvm" ]; then
    source ~/.rvm/scripts/rvm
fi

# If connected to a machine via SSH, show the hostname:
if [[ -n "$SSH_CONNECTION" ]]; then
	# Local
	export PS1="\w\$ "
else
	# Remote
	export PS1="[\H]\w\$ "
fi

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
