#!/bin/sh

export BASHRC_READ=true

AM_ROOT=false
if [ $UID == 0 ]; then
    AM_ROOT=true
fi

function command_exists
{
    if command -v $1 >/dev/null; then
        return 0
    else
        return 1
    fi
}

if [ $HOSTNAME = "zwerbach" ]; then
    function http_errors
    {
        tail -n 50 -f "$HOME/logs/$1/http/error.log"
    }
fi


# If connected to a machine via SSH, show the hostname:
if [[ -n "$SSH_CONNECTION" ]]; then
	# Local
	export PS1="\w\$ "
else
	# Remote
	export PS1="[\H]\w\$ "
fi

export GOPATH="$HOME/src/go"

PATH=$HOME/.bin:$HOME/src/dotfiles/bin:$PATH
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
export PATH

# TODO: If a VT, run the next line:
# setterm -powersave off -blank 0
