#!/usr/bin/env ruby

HOME        = ENV['HOME']
USERNAME    = ENV['USERNAME']
BASHRC_PATH = HOME + '/src/dotfiles/bash/bashrc'
BASHRC_WIN  = <<BASHRC
#!/bin/sh
export SwFLAGS="windows"
if [[ -n "$GITHUB_SHELL" ]]
    export SwFLAGS="cygwin"
    export HOME=/cygdrive/c/Users/$USERNAME
elsif 
    export SwFLAGS="github"
fi
source ~/.bashrc
BASHRC

def create_redir_bashrc(dir_path)
  File.open(dir_path +'/.bashrc', 'w+') do |f|
    f.puts BASHRC_WIN
  end
rescue
  puts "Failed to create bashrc in #{dir_path}: #$!"
end

def windows_setup
  # Create general bashrc
  create_redir_bashrc(HOME)

  # Create Cygwin bashrc
  create_redir_bashrc("/cygwin/home/#{USERNAME}")
end

def nixie_setup
  File.symlink(BASHRC_PATH, '~/.bashrc')
  puts 'Symlinked bashrc.'
rescue
  puts "Failed to symlink bashrc: #$!"
end

task :default do
  # Make redirecting ~/.bashrc

  case RUBY_PLATFORM
  when /linux/, /darwin/
    nixie_setup
  when /mswin/, /mingw32/
    windows_setup
  end

end
