#!/usr/bin/env ruby

HOME        = ENV['HOME']
USERNAME    = ENV['USERNAME']
BASHRC_PATH = HOME + '/src/dotfiles/bash/bashrc'


def windows_setup
  #TODO
end

def nixie_setup
  File.symlink(BASHRC_PATH, HOME + '/.bashrc')
  puts 'Symlinked bashrc.'
rescue
  puts "Failed to symlink bashrc: #$!"
end

task :default do
  # Make redirecting ~/.bashrc

  case RUBY_PLATFORM
  when /linux/, /darwin/
    nixie_setup
  when /mswin/, /mingw32/
    windows_setup
  end

end
